# fly.toml app configuration file generated for w-k-x-ok-tomorrow-genai-training-program on 2025-08-11T15:34:51-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'w-k-x-ok-tomorrow-genai-training-program'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
